import sqlmodel
"""add full_name and hashed_password to users

Revision ID: 01119c134531
Revises: cbb970636d04
Create Date: 2026-08-05 17:32:13.020868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01119c134531'
down_revision: Union[str, Sequence[str], None] = 'cbb970636d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=255), nullable=True))

    op.execute("UPDATE users SET full_name = name WHERE full_name IS NULL")
    op.execute("UPDATE users SET hashed_password = password_hash WHERE hashed_password IS NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hashed_password')
        batch_op.drop_column('full_name')
