import sqlmodel
"""add commission ledger and audit tables

Revision ID: 22b90887174e
Revises: f52737cbfd20
Create Date: 2026-07-18 15:50:01.814925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b90887174e'
down_revision: Union[str, Sequence[str], None] = 'aeb89f57bafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Fixed Patch ---
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute('DROP INDEX IF EXISTS ix_global_trade_bids_id;')
        op.execute('DROP INDEX IF EXISTS ix_loi_audit_trails_id;')
        op.execute('DROP INDEX IF EXISTS ix_market_orders_id;')
    # -------------------






    import sqlmodel
"""add commission ledger and audit tables

Revision ID: 22b90887174e
Revises: f52737cbfd20
Create Date: 2026-07-18 15:50:01.814925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b90887174e'
down_revision: Union[str, Sequence[str], None] = 'aeb89f57bafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Fixed Patch ---
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute('DROP INDEX IF EXISTS ix_global_trade_bids_id;')
        op.execute('DROP INDEX IF EXISTS ix_loi_audit_trails_id;')
        op.execute('DROP INDEX IF EXISTS ix_market_orders_id;')
    # -------------------








    inspector = sa.inspect(bind)
    
    # التأكد من إضافة العمود بأمان إذا كان مفقوداً
    if 'financial_transactions' in inspector.get_table_names():
        columns = [c['name'] for c in inspector.get_columns('financial_transactions')]
        if 'invoice_id' not in columns:
            with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
                batch_op.add_column(sa.Column('invoice_id', sa.Integer(), nullable=True))
                
    # تنظيف القيود لتفادي خطأ التكرار (مخصص لـ PostgreSQL فقط كي لا يكسر SQLite)

    """Upgrade schema."""
    # Ensure legacy databases have invoice_id before adding FK
        ALTER TABLE financial_transactions
        ADD COLUMN IF NOT EXISTS invoice_id INTEGER
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_financial_transactions_invoice', 'invoice', ['invoice_id'], ['id'])

    with op.batch_alter_table('global_trade_bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_trade_bids_id'), ['id'], unique=False)

    with op.batch_alter_table('loi_audit_trails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loi_audit_trails_id'), ['id'], unique=False)

    with op.batch_alter_table('market_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_orders_id'), ['id'], unique=False)

    with op.batch_alter_table('negotiation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negotiation_messages_id'), ['id'], unique=False)

    with op.batch_alter_table('negotiation_rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negotiation_rooms_id'), ['id'], unique=False)

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_id'))

    with op.batch_alter_table('negotiation_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negotiation_rooms_id'))

    with op.batch_alter_table('negotiation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negotiation_messages_id'))

    with op.batch_alter_table('market_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_orders_id'))

    with op.batch_alter_table('loi_audit_trails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loi_audit_trails_id'))

    with op.batch_alter_table('global_trade_bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_trade_bids_id'))

    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
