import sqlmodel
"""sync users schema

Revision ID: 601d14d14d30
Revises: b2b9ee547805
Create Date: 2026-07-17 06:03:03.106630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601d14d14d30'
down_revision: Union[str, Sequence[str], None] = 'b2b9ee547805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
