import sqlmodel
"""add global trade desk tables

Revision ID: 7ebc1990994d
Revises: a827a098f844
Create Date: 2026-07-19 00:45:12.187931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebc1990994d'
down_revision: Union[str, Sequence[str], None] = 'a827a098f844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_asset_type', sa.String(length=50), nullable=False),
    sa.Column('recommendation_title', sa.String(length=200), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_recommendations_id'), ['id'], unique=False)

    op.create_table('investor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investor_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investor_profiles_id'), ['id'], unique=False)

    op.create_table('market_price_tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('subtype', sa.String(length=50), nullable=True),
    sa.Column('price_average', sa.Float(), nullable=False),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('recorded_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_price_tickers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_price_tickers_id'), ['id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('org_type', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=True)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('global_trade_desk_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('target_country', sa.String(length=100), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('proforma_invoice_url', sa.String(length=255), nullable=True),
    sa.Column('packing_list_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_trade_desk_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_trade_desk_requests_id'), ['id'], unique=False)

    op.create_table('letters_of_intent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('deal_room_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('letters_of_intent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_letters_of_intent_id'), ['id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('assigned_role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_id'), ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('opportunity_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_id'), ['id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('commission_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', name='uq_commission_transaction')
    )
    with op.batch_alter_table('commission_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_ledger_id'), ['id'], unique=False)

    op.create_table('global_trade_bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=150), nullable=False),
    sa.Column('commission_percentage', sa.Float(), nullable=False),
    sa.Column('delivery_time_frame', sa.String(length=100), nullable=False),
    sa.Column('service_description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['global_trade_desk_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_trade_bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_trade_bids_id'), ['id'], unique=False)

    op.create_table('loi_audit_trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loi_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('action_details', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loi_id'], ['letters_of_intent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loi_audit_trails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loi_audit_trails_id'), ['id'], unique=False)

    op.create_table('market_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('listing_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_verified_by_agent', sa.Boolean(), nullable=True),
    sa.Column('verified_agent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_listings_id'), ['id'], unique=False)

    op.create_table('negotiation_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['mining_assets.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('negotiation_rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negotiation_rooms_id'), ['id'], unique=False)

    op.create_table('commission_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commission_id'], ['commission_ledger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_audit_logs_id'), ['id'], unique=False)

    op.create_table('deal_event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['negotiation_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_event_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_event_logs_id'), ['id'], unique=False)

    op.create_table('deal_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['negotiation_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_milestones_id'), ['id'], unique=False)

    op.create_table('market_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('offered_price', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['market_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_orders_id'), ['id'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['negotiation_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_id'), ['id'], unique=False)

    op.create_table('negotiation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['negotiation_messages.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['negotiation_rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('negotiation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negotiation_messages_id'), ['id'], unique=False)

    with op.batch_alter_table('escrow', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_escrow_id'), ['id'], unique=False)

    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_transactions_id'), ['id'], unique=False)
        batch_op.create_foreign_key('fk_fin_txn_invoice', 'invoice', ['invoice_id'], ['id'])
        batch_op.create_foreign_key('fk_fin_txn_user', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_invoice_id'), ['id'], unique=False)

    with op.batch_alter_table('mining_assets', schema=None) as batch_op:
        batch_op.alter_column('asset_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('other_description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_mining_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mining_assets_id'), ['id'], unique=False)
        batch_op.create_foreign_key('fk_mining_asset_owner', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_plans_id'), ['id'], unique=False)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_moderator', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_seller', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_importer', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_global_provider', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('is_global_provider')
        batch_op.drop_column('is_importer')
        batch_op.drop_column('is_seller')
        batch_op.drop_column('is_moderator')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_active')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_id'))

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_plans_id'))

    with op.batch_alter_table('mining_assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_mining_assets_id'))
        batch_op.drop_index(batch_op.f('ix_mining_assets_asset_type'))
        batch_op.alter_column('other_description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('asset_type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_id'))
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)

    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_financial_transactions_id'))

    with op.batch_alter_table('escrow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escrow_id'))
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)

    with op.batch_alter_table('negotiation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negotiation_messages_id'))

    op.drop_table('negotiation_messages')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_id'))

    op.drop_table('offers')
    with op.batch_alter_table('market_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_orders_id'))

    op.drop_table('market_orders')
    with op.batch_alter_table('deal_milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_milestones_id'))

    op.drop_table('deal_milestones')
    with op.batch_alter_table('deal_event_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_event_logs_id'))

    op.drop_table('deal_event_logs')
    with op.batch_alter_table('commission_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_audit_logs_id'))

    op.drop_table('commission_audit_logs')
    with op.batch_alter_table('negotiation_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negotiation_rooms_id'))

    op.drop_table('negotiation_rooms')
    with op.batch_alter_table('market_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_listings_id'))

    op.drop_table('market_listings')
    with op.batch_alter_table('loi_audit_trails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loi_audit_trails_id'))

    op.drop_table('loi_audit_trails')
    with op.batch_alter_table('global_trade_bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_trade_bids_id'))

    op.drop_table('global_trade_bids')
    with op.batch_alter_table('commission_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_ledger_id'))

    op.drop_table('commission_ledger')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_id'))

    op.drop_table('opportunities')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('letters_of_intent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_letters_of_intent_id'))

    op.drop_table('letters_of_intent')
    with op.batch_alter_table('global_trade_desk_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_trade_desk_requests_id'))

    op.drop_table('global_trade_desk_requests')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.drop_index(batch_op.f('ix_permissions_id'))

    op.drop_table('permissions')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('market_price_tickers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_price_tickers_id'))

    op.drop_table('market_price_tickers')
    with op.batch_alter_table('investor_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investor_profiles_id'))

    op.drop_table('investor_profiles')
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_id'))

    op.drop_table('ai_recommendations')
    # ### end Alembic commands ###
